#!/bin/sh 
set -x
echo hello
targetBinDir=$1
targetLibPerlDir=$2
targetTestDir=$3
checkoutFirst=$4

if [ "$targetTestDir" = "" ]; then
  echo "usage: install targetBinDir targetPerlLibDir targetTestDir -checkoutfirst";
  exit 1;
fi

mkdir -p $targetBinDir
mkdir -p $targetLibPerlDir
mkdir -p $targetTestDir

cd $COMPONENTS_HOME

if [ "$checkoutFirst" = "-checkoutfirst" ]; then
  cvs co \
  DotsBuild \
  Pipeline \
  DistribJob \
  DistribJobTasks \
  perl/lib/Common \
  perl/lib/Blast \
  perl/lib/FastaIndex.pm \
  perl/lib/FastaFile.pm \
  perl/lib/TO.pm \
  perl/bin/databases/dumpSequencesFromTable.pl \
  perl/bin/databases/deleteEntries.pl \
  perl/bin/Objects/ga \
  GUS/perl/bin/buildBlastClusters.pl \
  GUS/perl/lib/Objects/GUS_utils/GusApplication.pm \
  GUS/perl/lib/Objects/GA_plugins/UpdateDotsAssembliesWithCap4.pm \
  GUS/perl/lib/Objects/GA_plugins/MakeIndexWordLink.pm \
  GUS/perl/lib/Objects/GA_plugins/MarkAssemblySequencesBad.pm \
  GUS/perl/lib/Objects/GA_plugins/MakeAssemblySequences.pm \
  GUS/perl/lib/Objects/GA_plugins/ExtractAndBlockAssemblySequences.pm \
  GUS/perl/lib/Objects/GA_plugins/MakeRNAClustersForAssemblies.pm \
  GUS/perl/lib/Objects/GA_plugins/LoadNRDB.pm \
  GUS/perl/lib/Objects/GA_plugins/LoadTaxon.pm \
  GUS/perl/lib/Objects/GA_plugins/DeleteSimilarities.pm \
  GUS/perl/lib/Objects/GA_plugins/LoadBlastSimilaritiesPK.pm \
  GUS/perl/lib/Objects/GA_plugins/MakeIndexWordSimLink.pm \
  GUS/perl/lib/Objects/GA_plugins/InsertNewExternalSequences.pm \
  GUS/perl/lib/Objects/GA_plugins/MakeGoPredictions.pm \
  GUS/perl/lib/Objects/GA_plugins/CopyAASeqGoFuncToProtGoFunc.pm \
  GUS/perl/lib/Objects/GA_plugins/DeleteGoPredictions.pm \
  GUS/perl/lib/Objects/GA_plugins/LoadEPCR.pm \
  GUS/perl/lib/Objects/GA_plugins/AssignLibraryDistributionToAssemblies \
  GUS/perl/lib/Objects/GA_plugins/FrameFinder \
  GUS/perl/lib/Objects/GA_plugins/AssignSequenceDescription.pm
fi

# bin
/bin/cp DotsBuild/bin/* $targetBinDir
/bin/cp Pipeline/bin/* $targetBinDir
/bin/cp DistribJob/bin/* $targetBinDir
/bin/cp DistribJobTasks/bin/* $targetBinDir
/bin/cp perl/bin/databases/dumpSequencesFromTable.pl $targetBinDir
/bin/cp perl/bin/databases/deleteEntries.pl $targetBinDir
/bin/cp perl/bin/Objects/ga $targetBinDir
/bin/cp GUS/perl/bin/buildBlastClusters.pl $targetBinDir

# perl lib
/bin/rm -rf $targetLibPerlDir/DotsBuild
/bin/rm -rf $targetLibPerlDir/Pipeline
/bin/rm -rf $targetLibPerlDir/DistribJob
/bin/rm -rf $targetLibPerlDir/DistribJobTasks
/bin/rm -rf $targetLibPerlDir/Common
/bin/rm -rf $targetLibPerlDir/Blast
/bin/cp -r DotsBuild/lib/perl/DotsBuild $targetLibPerlDir
/bin/cp -r Pipeline/lib/perl/Pipeline $targetLibPerlDir
/bin/cp -r DistribJob/lib/perl/DistribJob $targetLibPerlDir
/bin/cp -r DistribJobTasks/lib/perl/DistribJobTasks $targetLibPerlDir
/bin/cp -r perl/lib/Common $targetLibPerlDir
/bin/cp -r perl/lib/Blast $targetLibPerlDir
/bin/cp -r perl/lib/FastaIndex.pm $targetLibPerlDir
/bin/cp -r perl/lib/FastaFile.pm $targetLibPerlDir
/bin/cp -r perl/lib/TO.pm $targetLibPerlDir
/bin/cp -r GUS/perl/lib/Objects $targetLibPerlDir

# test
/bin/rm -rf $targetTestDir/DistribJobTasks
/bin/rm -rf $targetTestDir/DistribJob
/bin/cp -r DistribJobTasks/test/ $targetTestDir/DistribJobTasks
/bin/cp -r DistribJob/test/ $targetTestDir/DistribJob

chmod +x $targetBinDir/*
 
